### ISSUE TITLE
[BUG] Doesent spoof coords when using BetterF3

### ISSUE THREAD

**Issue by Omena0** [agent-LuluDodo/DefinitelyMyCoords#1]
## System
-  Minecraft: 1.19.3
- Mod Version: 1.1
- OS: Windows

## Describe the bug
Does not hide coords ect when using BetterF3

## To Reproduce
1. Install DMC and BetterF3
2. Enable coordinate spoof
3. Open F3

## Expected behavior
Coords spoofed 

## Additional context
BetterF3: https://modrinth.com/mod/betterf3

**Comment by agent-LuluDodo** [comment]
Working on a fix, should be done in a couple of days.

**Comment by Omena0** [comment]
Thanks!
W mod btw

**Comment by agent-LuluDodo** [comment]
I uploaded the new version (1.2) to modrinth.
If you encounter another problem, feel free to create a new report. 
:)

**Comment by Omena0** [comment]
Thanks!
