### ISSUE TITLE
[Bug] Doesn't Hide Target Block

### ISSUE THREAD

**Issue by Its3rr0rsWRLD** [agent-LuluDodo/DefinitelyMyCoords#10]
### Minecraft version

1.20.4

### Mod version

1.2.4

### Operating system

Windows

### Describe the bug

When looking at a block, it still shows the actual coords.

### To Reproduce

Look at a block in F3

### Expected behavior

Spoof cords

**Comment by agent-LuluDodo** [comment]
That's a really stupid oversight on my side xD

It works if you use [BetterF3](https://modrinth.com/mod/betterf3/version/9.0.2) with the mod, but I should be able to fix this tomorrow.

Thanks for reporting!

**Comment by agent-LuluDodo** [comment]
Fixed in [1.2.8](https://modrinth.com/mod/definitelymycoords/version/HOzdMmqZ).
