### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by HerobaneNair** [agent-LuluDodo/DefinitelyMyCoords#2]
## System
- Minecraft version [e.g. 1.19.4]
- Mod version [e.g. 1.2]
- Operating system [e.g. Windows]

## Describe what you were doing
I downloaded the mod and tried joining a server. The server said I had a NoSuchMethod error when calling net.kyori.adventure.text.component net.minecraft.class_2561

**Comment by agent-LuluDodo** [comment]
Hi, @HerobaneNair can you please attach a list of the mods you were using and the minecraft version you played on and a crash report if possible? thx

**Comment by agent-LuluDodo** [comment]
I can't help you without that information, so I'm going to close the issue.
