### ISSUE TITLE
more hiding

### ISSUE THREAD

**Issue by pizzav-xyz** [agent-LuluDodo/DefinitelyMyCoords#3]
### The problem

it doesnt hide it to other mods like xaero minimap

### The solution/feature

also tell other mods the fake location

### Alternatives

/

**Comment by agent-LuluDodo** [comment]
Thanks, added this feature: https://modrinth.com/mod/definitelymycoords/version/1.2.3

If you find more mods which don't display the fake location, please tell me :)

**Comment by pizzav-xyz** [comment]
> Thanks, added this feature: https://modrinth.com/mod/definitelymycoords/version/1.2.3
> 
> If you find more mods which don't display the fake location, please tell me :)

will you like it if i send cheats?

**Comment by agent-LuluDodo** [comment]
Sorry, but I won't add support for cheats.

**Comment by pizzav-xyz** [comment]
> Sorry, but I won't add support for cheats.

ok because i would say meteor client
