### ISSUE TITLE
discord streaming

### ISSUE THREAD

**Issue by pizzav-xyz** [agent-LuluDodo/DefinitelyMyCoords#4]
### The solution/feature

add a toggle that only enables the mod when discord streaming is detected

**Comment by pizzav-xyz** [comment]
https://discord.com/developers/docs/game-sdk/getting-started

**Comment by agent-LuluDodo** [comment]
Hi, thanks for the suggestion, but working with external applications is a lot of work, and I'm not willing to invest the time into this project.
