### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sickomc** [agent-LuluDodo/DefinitelyMyCoords#6]
### Minecraft version

1.20.4

### Mod version

1.2.2

### Operating system

Windows

### Describe the bug

Doesnt work on 1.20.4

### To Reproduce

Launch minecraft fabric with the mod installed and gives a error

### Expected behavior

Launch minecraft

**Comment by JackyXYZGaming** [comment]
yeah im getting the same thing on 1.20.1

**Comment by agent-LuluDodo** [comment]
Sorry for the long wait, should be fixed in 1.2.4. 
Downloads: [1.20.4](https://modrinth.com/mod/definitelymycoords/version/iK1I5XlZ), [1.20.1](https://modrinth.com/mod/definitelymycoords/version/K1nih2x7)
