### ISSUE TITLE
[Crash] 

### ISSUE THREAD

**Issue by JackyXYZGaming** [agent-LuluDodo/DefinitelyMyCoords#8]
### Minecraft version

1.20.1

### Mod version

1.2.2

### Operating system

Windows 11

### Mods

![image_2024-06-04_172102599](https://github.com/agent-LuluDodo/DefinitelyMyCoords/assets/119239250/2bbe90c0-09bc-4918-88fd-d265fd9049bd)

### Describe what you were doing

I launch minecraft and it gives me a crash error immediately

### To Reproduce

Put Definitely My Cords 1.2.4 mod into folder
Launch Minecraft Fabric
Crashes Upon Launch

### Crash report

https://mclo.gs/TxZsfnV

### Additional context

I have a lot of mods so I don't know which ones are conflicting with each other if they are.
![Screenshot 2024-06-04 172052](https://github.com/agent-LuluDodo/DefinitelyMyCoords/assets/119239250/a4e0285b-a147-43ca-8071-b09d2f6715fd)

**Comment by agent-LuluDodo** [comment]
Looks like some incompatibility with entity-view-distance and/or iris. 

Have you made sure that it works without my mod?

I will continue looking into this on the weekend :)

**Comment by agent-LuluDodo** [comment]
Btw, you have "voicechat-fabric" twice in your mods list, as well as "fabric-language-kotlin". I also don't know what 1.20.1.jar is, since minecraft doesn't belong in the mod folder (as far as I know).

**Comment by JackyXYZGaming** [comment]
> Looks like some incompatibility with entity-view-distance and/or iris.
> 
> Have you made sure that it works without my mod?
> 
> I will continue looking into this on the weekend :)

Ok seems like i got it fixed the incompatibilities were Iris, entity-view-distance, and magiclib. I wont really miss out on magiclib or entity-view-distance but Iris is a need for me. Is it possible you could try to make this mod compatible with Iris? If so, thank you!

**Comment by JackyXYZGaming** [comment]
> Btw, you have "voicechat-fabric" twice in your mods list, as well as "fabric-language-kotlin". I also don't know what 1.20.1.jar is, since minecraft doesn't belong in the mod folder (as far as I know).

Although it works in the F3 menu it doesnt work with sodiums cord overlay is there any way you could make the cords spoof in there too?
![image_2024-06-05_193428346](https://github.com/agent-LuluDodo/DefinitelyMyCoords/assets/119239250/ae42997e-51d6-420a-9a47-9b958528b310)
To clarify the mod is set to 500x 500y 500z although it changes in the F3 menu it doesn't change the sodium overlay coordinates

**Comment by agent-LuluDodo** [comment]
Fixed the crash with Iris and added compatibility for Sodium Extra's Coords Module. (Haven't tried, but this could have also fixed the issue with entity-view-distance and magiclib)

Download: [1.20.1](https://modrinth.com/mod/definitelymycoords/version/pKAZbHxf)
