### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by JackyXYZGaming** [agent-LuluDodo/DefinitelyMyCoords#9]
### The problem

Doesn't have a way back to reset your coordinates to your original set of coordinates before spoof

### The solution/feature

A reset button to disable the spoof and set your coordinates to your actual location

### Additional context

Could be a keybind or a reset button in the F6 menu

**Comment by agent-LuluDodo** [comment]
You can change it back to the original by setting the mode to **absolute** and the coords to **0 0 0**. But it's a good idea to add an extra button for this functionality.

**Comment by agent-LuluDodo** [comment]
Added mode Vanilla, which doesn't spoof your coords. Also added KeyBindings for every mode.

Download: [1.19.3-1.19.4](https://modrinth.com/mod/definitelymycoords/version/1.2.6) [1.20-1.20.1](https://modrinth.com/mod/definitelymycoords/version/jfmPwQm0) [1.20.2](https://modrinth.com/mod/definitelymycoords/version/sY5QIw3I) [1.20.3-1.20.4](https://modrinth.com/mod/definitelymycoords/version/X9Eg52Fc)
